apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3-web
spec:
  replicas: 4
  selector:
    matchLabels:
      app3: web
  template:
    metadata:
      labels:
        app3: web
    spec:
      containers:
      - name: nginx
        image: nginx:1.17-alpine
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app3: web
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
