apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3-web
spec:
  replicas: 30
  selector:
    matchLabels:
      app3: web
  template:
    metadata:
      labels:
        app3: web
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
